### 垃圾邮件分类

使用SVM来构建垃圾邮件过滤器

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from scipy.io import loadmat

In [27]:
spam_train = loadmat('./datasets/spamTrain.mat')
spam_test = loadmat('./datasets/spamTest.mat')

spam_train, spam_test

({'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Nov 13 14:27:25 2011',
  '__version__': '1.0',
  '__globals__': [],
  'X': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 1, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
  'y': array([[1],
         [1],
         [0],
         ...,
         [1],
         [0],
         [0]], dtype=uint8)},
 {'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Nov 13 14:27:39 2011',
  '__version__': '1.0',
  '__globals__': [],
  'Xtest': array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
  'ytest': array([[1],
         [0],
         [0],
         [1],
         [1],
         [1],
         [1],
         [

In [28]:
X = spam_train['X']
Xtest = spam_test['Xtest']
y = spam_train['y'].ravel()
ytest = spam_test['ytest'].ravel()

X.shape, y.shape, Xtest.shape, ytest.shape

((4000, 1899), (4000,), (1000, 1899), (1000,))

In [29]:
from sklearn import svm
# 分类器
svc = svm.SVC()
svc.fit(X, y)

SVC()

In [30]:
# np.round() 对给定的数组进行四舍五入，能够指定精度
print(svc.score(X, y))
print('Training accuracy = {0}%'.format(np.round(svc.score(X, y) * 100, 2)))
print('Test accuracy = {0}%'.format(np.round(svc.score(Xtest, ytest) * 100, 2)))

0.99325
Training accuracy = 99.32%
Test accuracy = 98.7%


可视化结果

In [31]:
# 生成对角矩阵,主对角线全1，其余全0
kw = np.eye(1899)
print(kw)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [32]:
kw[:3,:]

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [33]:
spam_val = pd.DataFrame({'idx':range(1899)})
print(spam_val)

       idx
0        0
1        1
2        2
3        3
4        4
...    ...
1894  1894
1895  1895
1896  1896
1897  1897
1898  1898

[1899 rows x 1 columns]


In [34]:
spam_val['isspam'] = svc.decision_function(kw)

In [35]:
spam_val

idx    isspam
0        0 -0.093653
1        1 -0.083078
2        2 -0.109401
3        3 -0.119685
4        4 -0.165824
...    ...       ...
1894  1894  0.101613
1895  1895 -0.016065
1896  1896 -0.151573
1897  1897 -0.109022
1898  1898 -0.091970

[1899 rows x 2 columns]

In [36]:
# 对每一列数据进行统计，包括计数，均值，std，各个分位数等
spam_val['isspam'].describe()

count    1899.000000
mean       -0.110039
std         0.049094
min        -0.428396
25%        -0.131213
50%        -0.111985
75%        -0.091973
max         0.396286
Name: isspam, dtype: float64

In [37]:
decision = spam_val[spam_val['isspam'] > -0.55]
decision

idx    isspam
0        0 -0.093653
1        1 -0.083078
2        2 -0.109401
3        3 -0.119685
4        4 -0.165824
...    ...       ...
1894  1894  0.101613
1895  1895 -0.016065
1896  1896 -0.151573
1897  1897 -0.109022
1898  1898 -0.091970

[1899 rows x 2 columns]